### PR TITLE
All Translation Redesign

### PR DESCRIPTION
**Pull request by yatil**
First attempt at redesigning the all translations page and also incorporating standards/guidelines

TODO:

- [x] Fix nesting
- [x] Fix showing HTML :-)
- [x] Ask @slhenry if that is what we want to do

### CODE REVIEW

**Comment by slhenry** [comment]
+1 to DLs and bold DTs = good for skimming in language

I'm mildly thinking:
* Not have separate section for "Translated Standards/Guidelines". Possibly add "Standard" after the link (if easy to do)
* Don't need to indicate "Authorized".

Happy to discuss!

**Comment by yatil** [comment]
> Not have separate section for "Translated Standards/Guidelines". Possibly add "Standard" after the link (if easy to do)

Hm. I would need to shuffle the standards and guidelines into the other resources so that they can be found alphabetically. Having them separate is much easier. (I think it might also be easier for users to find them.)

> Don't need to indicate "Authorized".

I can remove it. Are we planning to list unauthorized translations, too?

**Comment by slhenry** [comment]
> Having them separate is much easier.

OK.

Don't need "Translated Standards/Guidelines" -- just "Standards/Guidelines" -- and we already have the translation for that in the yml -- just need to get the ones we don't have...

> Are we planning to list unauthorized translations, too?

um... good question... I was thinking that we would... however they're not on our site so some issues with  it... however, W3C links to them... /me will open separate issue to get more feedback...

**Comment by yatil** [comment]
- [ ] English Standards/Guidelines if not available

**Comment by yatil** [comment]
@slhenry I have now used “Standards/Guidelines” in English by default, we don’t have translations for that at the moment.

Let me know if OK to publish.

**Comment by slhenry** [comment]
Yeah! [insert cheering emoji here]

I updated the intro text. (I see that you put it in a box titled "Summary" – but it's not quite a summary – since it has info that's not elsewhere on the page. I guess it's not a big deal.)

A few things:

## Add listings
I reviewed all of these and am comfortable linking to them.
* [ ] To Simplified Chinese listing, under Standards/Guidelines, add: 无障碍创作工具指南(ATAG) 2.0 https://www.w3.org/Translations/ATAG20-zh/
* [ ] Add Hebrew https://www.isoc.org.il/files/w3c-wai/guidelines.html
* [ ] Add Hungarian http://www.w3c.hu/forditasok/WCAG20/
* [ ] Add Japanese https://waic.jp/docs/WCAG20/Overview.html
* [ ] Add Polish http://fdc.org.pl/wcag2/
* [ ] Add Spanish http://www.sidar.org/traducciones/wcag20/es/

## Language headings

* [ ] I think "(Greek, Modern)" would be better as just "(Greek)"

* [ ] I'm not sure about "Català (Catalan; Valencian)". Based on [translation]( https://www.w3.org/Translations/WCAG20-ca/) I'm thinking it can just be "Català (Catalan)" or even just "Catalan" based on their title: "Traducció catalana autoritzada"? We can ask Martin &/or translators if needed.

* [ ] In English, best to say "Brazilian Portuguese", "European Portuguese", "Simplified Chinese", "Traditional Chinese". Not sure the best way to handle that in this page – for usability and technically. For English, see how it's done in [WCAG 2.o Portuguese listing]( https://www.w3.org/WAI/standards-guidelines/wcag/translations/#pt) – with a single row and multiple listings. For this page, I wonder about an {h2} for Portuguese and {h3} for the different ones? Probably good for usability – maybe not easy technically?
. Brazilian Portuguese Authorized Translation is titled "Tradução Autorizada em Português do Brasil"
. European Portuguese Authorized Translation is titled "Tradução Autorizada em Português Europeu"
. [W3C Translations list](https://www.w3.org/Translations/) uses "Português-BR (Brazilian Portuguese)"
… I'll ask Reinaldo and Caroline, and will CC you in the e-mail.

**?: About the order** – is that happening programmatically? (It seems a bit odd, yet probably not worth messing with.)

## Other

* [ ] To the Standards/Guidelines listings, add the LTO or Translator. Can get that from [W3C Translations list]( https://www.w3.org/Translations/#s-WCAG20) if that's easiest

* [ ] Typo – quote(") at then end of: English title: Understanding WCAG 2.0"

* [ ] when publish, please do link check

<hr>

I guess we want to add to the yml file "Standards/Guidelines", and solicit translations of that, and then use the translated term when we have enough?

And, while we're at it, we should also add to the yml file the other words in the main nav , so we have them when those pages are translated?

**Comment by yatil** [comment]
@slhenry okay so we WANT to add unauthorized translations. That changes the scope and needs more work.

I’ll work on the things I need to know to make it happen so we can talk about them on Tuesday and I can implement them eventually.

**Comment by yatil** [comment]
> I reviewed all of these and am comfortable linking to them.
> [list of translations]

Is that a task that you will do or that I’m supposed to do?

> Language headings

They can be changed in the wai-website-data repository: https://github.com/w3c/wai-website-data/blob/master/lang.json

I’m not comfortable to make some of those changes as I don’t speak these languages and therefore don’t know how to address them properly.

> In English, best to say "Brazilian Portuguese", "European Portuguese", "Simplified Chinese", "Traditional Chinese". Not sure the best way to handle that in this page – for usability and technically. For English, see how it's done in WCAG 2.o Portuguese listing – with a single row and multiple listings. For this page, I wonder about an {h2} for Portuguese and {h3} for the different ones? Probably good for usability – maybe not easy technically?

We don’t have any way to do that. The `pt` and `pt-BR` are distinct translations.

> ?: About the order – is that happening programmatically? (It seems a bit odd, yet probably not worth messing with.)

The order does not come out as I wished it would at the moment, unsure why, could improve.

> To the Standards/Guidelines listings, add the LTO or Translator. Can get that from W3C Translations list if that's easiest

What would that be described as? “Translating Organization”? We would need to get translations for that for all languages. Or do we go with just “Translator:” where we already have translations?

> when publish, please do link check

I am unsure what that means.

> I guess we want to add to the yml file "Standards/Guidelines", and solicit translations of that, and then use the translated term when we have enough?

Maybe. I’m just thinking of getting this out the door.

> And, while we're at it, we should also add to the yml file the other words in the main nav , so we have them when those pages are translated?

No, those will be translated with the pages and not connected to the translations here.

**Comment by yatil** [comment]
> (I see that you put it in a box titled "Summary" – but it's not quite a summary – since it has info that's not elsewhere on the page. I guess it's not a big deal.)

I’m happy to change the text of “Summary”, I just wanted some resemblance of the other pages and as we are starting almost every page with a box, I added it here, too.

**Comment by yatil** [comment]
I think I have addressed most of the checks above, but the order/sort issue.

- [ ] Fix sorting

**Comment by slhenry** [comment]
>> I reviewed all of these and am comfortable linking to them.

> Is that a task that you will do or that I’m supposed to do?

I will do.

> I’m not comfortable to make some of those changes as I don’t speak these languages and therefore don’t know how to address them properly.

Let me know which ones you want me to check on.

>> To the Standards/Guidelines listings, add the LTO or Translator. Can get that from W3C Translations list if that's easiest

> What would that be described as? “Translating Organization”? We would need to get translations for that for all languages. Or do we go with just “Translator:” where we already have translations?

That's fine for now. (We can see if anyone balks and wants "Lead translating organization (LTO):")

>> when publish, please do link check

> I am unsure what that means.

Please check that the links work.
 
>> I guess we want to add to the yml file "Standards/Guidelines", and solicit translations of that, and then use the translated term when we have enough?

> Maybe. I’m just thinking of getting this out the door.

+1 to get this iteration published, and defer this to later iteration!

>> And, while we're at it, we should also add to the yml file the other words in the main nav , so we have them when those pages are translated?

> No, those will be translated with the pages and not connected to the translations here.

/me knows not connected to translations here – was just thinking ahead…

**Comment by yatil** [comment]
@slhenry 

>>> I reviewed all of these and am comfortable linking to them.
>> Is that a task that you will do or that I’m supposed to do?
> I will do.

Already done in https://github.com/w3c/wai-website/pull/167/commits/fe76fb81b6990bc6979f9d7092bfb88a663aa551

>> I’m not comfortable to make some of those changes as I don’t speak these languages and therefore don’t know how to address them properly.
> Let me know which ones you want me to check on.

Basically all the descriptions for languages in the language file: https://github.com/w3c/wai-website-data/blob/master/lang.json

(I made the changes above, but I’m not sure about removing Valencian. Also, the Brazilian Portuguese/European Portuguese needs to be addressed. I could imagine some strong feelings by people from Portugal.)

>>> To the Standards/Guidelines listings, add the LTO or Translator. Can get that from W3C Translations list if that's easiest
>> What would that be described as? “Translating Organization”? We would need to get translations for that for all languages. Or do we go with just “Translator:” where we already have translations?
> That's fine for now. (We can see if anyone balks and wants "Lead translating organization (LTO):")

Done.

>>> when publish, please do link check
>> I am unsure what that means.
> Please check that the links work.

I copied the links from W3.org and so I guess they all work, most of them I clicked on. (SiteImprove has a link checker that we can use.)

>>> I guess we want to add to the yml file "Standards/Guidelines", and solicit translations of that, and then use the translated term when we have enough?
>> Maybe. I’m just thinking of getting this out the door.
> +1 to get this iteration published, and defer this to later iteration!

If the wording is set, it takes the translation, otherwise the English fallback. Same for "Translator:".

>>> And, while we're at it, we should also add to the yml file the other words in the main nav , so we have them when those pages are translated?
>> No, those will be translated with the pages and not connected to the translations here.
> /me knows not connected to translations here – was just thinking ahead…

No problem. :-)

**Comment by slhenry** [comment]
This is looking great, @yatil!

I would be comfortable publishing it now. (I'm eager to point to this updated version. :-)
When we get replies about the language listings, we can update.
If you want to wait for that or other, that's OK with me.
If you want to publish now, that's OK with me. ;-)

**Comment by slhenry** [comment]
I updated Portuguese in the lang file.

I **_think_** it would be best if "Simplified Chinese" was sorted by "Chinese" for alphabetical order.

**Comment by yatil** [comment]
@slhenry It is sorted by the abbreviation (zh-hans). We can sort by the name (Simplified Chinese) instead. Or we introduce a sort-by Attribute in the languages file that we use for sorting. While the last one is possible, it would complicate programming and take significant effort. 

If we want to do that, please open a new issue with a feature request. (Commenting on closed issues or PRs risks losing them  and we don’t want to re-open merges PRs when possible.)

**Pull request merged**
