### PR TITLE
Remove APG from search index

### PR DESCRIPTION
**Pull request by yatil**
Band-aid fix for #357

### CODE REVIEW

**Comment by shawna-slh** [comment]
What are possible unintended consequences?

@howard-e @iadawn

**Comment by howard-e** [comment]
@shawna-slh @yatil 

After discussing with @alflennik, we found that the violating pages are inside [ARIA/apg/patterns/landmarks](https://github.com/w3c/wai-aria-practices/tree/main/ARIA/apg/patterns/landmarks/examples).

Historically, these pages didn’t follow the expected format to allow them to include the correct front matter metadata like the other pages in WAI APG do, because of unique functionality on those pages that wouldn’t work when included in the WAI website. There has already been discussions in the past to rewrite these pages to align with how other pages work, not just for the WAI APG’s purposes, so I’d figure that change is still coming.

> What are possible unintended consequences?

For the technical aspect, I’m unsure but I’d think removing APG from the search wouldn’t be preferred. Is it possible to deindex that specific list of 12 pages / paths?

cc @mcking65

**Comment by shawna-slh** [comment]
> Is it possible to deindex that specific list of 12 pages / paths?

Happy to do that if you provide the fix.

**Comment by howard-e** [comment]
> > Is it possible to deindex that specific list of 12 pages / paths?
> 
> Happy to do that if you provide the fix.

Noted thanks, I've submitted #362.

**Comment by mcking65** [comment]
Thank you @howard-e!

Yes, removing just those 12 pages is the best approach.

The offending landmark pages have been on my mind ever since the redesign launch last year ... they are a bit of a nightmare. Just last weekend I was working on gathering the related issues and assembling a plan to present to the task force. I still have some work to do before I have a coherent proposal. I'd like to get fixing them added to the 2023 milestones if I can drum up the needed people power.

So, I hope that removal is a short-lived fix. @howard-e, please create an issue in wai-aria-practices to track removing it when the time is right. I will link that issue to the landmark example rework plan when I have it in place.

**Comment by howard-e** [comment]
> Yes, removing just those 12 pages is the best approach.
> 
> The offending landmark pages have been on my mind ever since the redesign launch last year ... they are a bit of a nightmare. Just last weekend I was working on gathering the related issues and assembling a plan to present to the task force. I still have some work to do before I have a coherent proposal. I'd like to get fixing them added to the 2023 milestones if I can drum up the needed people power.
> 
> So, I hope that removal is a short-lived fix. @howard-e, please create an issue in wai-aria-practices to track removing it when the time is right. I will link that issue to the landmark example rework plan when I have it in place.

Done in https://github.com/w3c/wai-aria-practices/issues/270

**Comment by remibetin** [comment]
Thanks @yatil for this proposed solution.

I have merged https://github.com/w3c/wai-website/pull/362 to only exclude the concerned pages.

**Pull request closed without merging**
