### PR TITLE
translation social image and text

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by slhenry** [comment]
Hey @yatil - please QA and publish. Thanks!

**Comment by yatil** [comment]
@slhenry I see you flipped the translation icon, which means the Japanese sign is mirrored. I suggest flipping the Japanese back before we publish.

The image does not show up in the card validator https://cards-dev.twitter.com/validator which might mean that the image format is slightly wrong. 

For the business case, we use a 800 × 418 pixels image with 72 pixels/inch

The image for the translations has 1024 × 512 pixels with 144 pixels/inch

I guess that makes it incompatible (Twitter is very picky with those image dimensions).

**Comment by slhenry** [comment]
From [Twitter itself](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html):
> Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported.

image is 1024×512 pixels 196KB png

Maybe there is a different problem, e.g., location of the image?

**Comment by yatil** [comment]
> Maybe there is a different problem, e.g., location of the image?

I double-checked that the image was available under the location given in the HTML. I have the preview rendered again and will try again later and see if it works now.

**Comment by slhenry** [comment]
thanks!

**Comment by slhenry** [comment]
uurrgg -- still not working :(

**Comment by slhenry** [comment]
( /me notes looks like New in 2.1 no worky eaither https://twitter.com/w3c_wai/status/1129140686656294912 )

**Comment by slhenry** [comment]
https://wai-website.netlify.com/content-images/social-translations.png  = not found

**Comment by yatil** [comment]
> https://wai-website.netlify.com/content-images/social-translations.png = not found

Yes, it can’t be there because I have not merged this Pull Request yet. (As always.)

> /me waiting to tweet

I’ll only get to it tomorrow, I’m out of office for several hours now (it is 9pm here).

Wait until I have the time to do what you ask (QA and give you the OK for it).

**Comment by yatil** [comment]
Ah, the deploy preview uses the non-deploy preview URL for social images… that is… unfortunate. Let’s see if it works after merging. It should.

**Comment by yatil** [comment]
@slhenry Works now in the deploy preview, uploading.

Screenshot 2019-07-29 at 21 40 58

**Comment by yatil** [comment]
@slhenry Tweet away!

**Comment by slhenry** [comment]
THANKS A MILLION!

**Pull request merged**
