### PR TITLE
Images Tutorial: Fix broken links

### PR DESCRIPTION
**Pull request by remibetin**
Resolves https://github.com/w3c/wai-website/issues/753

Previews:
- [Example Link](https://deploy-preview-843--wai-website.netlify.app/example-link/) page
- [Informative Images](https://deploy-preview-843--wai-website.netlify.app/tutorials/images/informative/) page
- [Decorative Images](https://deploy-preview-843--wai-website.netlify.app/tutorials/images/decorative/) page

## Context

[Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/) and [Informative Images](https://www.w3.org/WAI/tutorials/images/informative/) were containing links to https://www.w3.org/WAI/tutorials/images/beyond.html that led to a 404 page.

After investigation:
- the links never worked on live website (see [Web Archive](https://web.archive.org/web/20220801000000*/https://www.w3.org/WAI/tutorials/images/beyond.html))
- in the Editor’s draft, the link was leading to https://www.w3.org/WAI/EO/Drafts/tutorials/beyond/. See https://www.w3.org/WAI/EO/Drafts/tutorials/images/decorative/. 
This page was not re-created on the new website (probably unintentionally).

## Solution

This PR adds a new "Example Link" page to provide a destination to example links. Its permalink will be  https://www.w3.org/WAI/example-link/

To avoid broken links, this PR:
- updates the links in [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/) and [Informative Images](https://www.w3.org/WAI/tutorials/images/informative/)
- adds a redirect from https://www.w3.org/WAI/tutorials/images/beyond.html to https://www.w3.org/WAI/example-link/

### CODE REVIEW

**Comment by remibetin** [comment]
@shawna-slh Ready to review. I am just wondering if we want to keep this page under /tutorials/images/ or if it could be used more broadly. 

Do you think of other WAI resources that could use example links and point to this new page?

**Comment by shawna-slh** [comment]
I don't think of other uses right now; however, it seems like a good idea to have it at a higher level so it's available more broadly.

**Review by shawna-slh — APPROVED** [review]
Thanks!

**Comment by remibetin** [comment]
Thanks @shawna-slh 

> I don't think of other uses right now; however, it seems like a good idea to have it at a higher level so it's available more broadly.

I have moved the page to the root of the WAI website (permalink will be https://www.w3.org/WAI/example-link/). I have also updated the footer to state this page was initially developed as part of the Images Tutorials.

Preview is at https://deploy-preview-843--wai-website.netlify.app/example-link/

What do you think?

**Comment by shawna-slh** [comment]
> I have also updated the footer to state this page was initially developed as part of the Images Tutorials.

Thanks for the idea.

I don't think that's needed, and is just distracting.

Any reason to have a footer on this page at all?

**Comment by remibetin** [comment]
> Any reason to have a footer on this page at all?

We will probably not update this page often, so I am fine going without.

**Comment by shawna-slh** [comment]
> We will probably not update this page often

and even if we do, it's not important to have an updated date on this :-)

**Comment by remibetin** [comment]
Updated, see https://deploy-preview-843--wai-website.netlify.app/example-link/

**Comment by remibetin** [comment]
QA done: ✅ OK

**Pull request merged**
